# conda environment description file for the analysis-grace environment
#
# Create a conda environment in which to run Jupyter Notebooks in this directory with:
#
#   $ conda env create -f environment.yaml
#   $ conda activate analysis-grace
#
# To add new packages to the environment,
# add them to the dependencies list below,
# then update the activated environment with:
#
#   (analysis-grace)$ conda env update -f environment.yaml

name: analysis-grace

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - bottleneck
  - cartopy
  - cliff
  - cmocean
  - coverage
  - dask
  - f90nml
  - gsw
  - ipdb
  - ipython
  - jupyterlab
  - lxml
  - matplotlib
  - nbsphinx
  - netCDF4
  - numpy
  - openpyxl
  - pandas
  - pillow
  - pip
  - pyproj
  - pytest
  - python=3
  - pytz
  - python-dateutil
  - pyyaml
  - requests
  - retrying
  - scipy
  - shapely
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - xarray
  - Parcels
  - ffmpeg

  - pip:
    - angles
